name: Deploy on PR Merge to Main

on:
  pull_request:
    branches:
      - main
    types:
      - closed # Dispara quando o PR é fechado

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: sa-east-1
  ROLE_TO_ASSUME: arn:aws:iam::915153720516:role/GitHubActions-ECS-Deploy-Role
  ECR_REPOSITORY: fcg-users-service
  ECS_CLUSTER: fcg-cluster-fiap
  ECS_SERVICE: fcg-users-service
  CONTAINER_NAME: fcg-users-service-container
  WORKING_DIR: ./infra # Apontado para a pasta infra

jobs:
  deploy-on-merge:
    name: Apply Infra, Push Image and Deploy to ECS
    # Só executa se o PR tiver sido realmente MESCLADO
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      # 1. Executa o Terraform na pasta ./infra
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.0"

      - name: Terraform Init & Apply
        run: |
          cd ${{ env.WORKING_DIR }}
          terraform init
          terraform apply -auto-approve

      # 2. Login no Amazon ECR
      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # 3. Build e Push da Imagem Docker
      - name: Build, Tag, and Push Image to ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

      # 4. Atualiza a Task Definition do ECS
      - name: Render ECS Task Definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: .aws/task-definition.json
          container-name: ${{ env.CONTAINER_NAME }}
          image: ${{ steps.build-image.outputs.image }}

      # 5. Executa o Deploy no Cluster ECS
      - name: Deploy Amazon ECS Task Definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true